name: Test SVA

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run --help on main.py
        run: python -m sidereal_visibility_avg.main --help

      - name: Run testcase
        run: python -m sidereal_visibility_avg.main --only_lst_mapping .github/testdata/test?.ms

      - name: Run testcase with chunk factor
        run: python -m sidereal_visibility_avg.main --chunk_factor 2345.1 --only_lst_mapping .github/testdata/test?.ms

      - name: Run testcase with chunk factor
        run: python -m sidereal_visibility_avg.main --chunk_factor 2345.1 --interpolate_uvw .github/testdata/test?.ms
