name: Test SVA

on:
  pull_request:  # Run on any PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Disable Microsoft Repo
        run: |
          sudo sed -i 's/^deb/#deb/' /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update

      - name: Install Singularity
        run: |
          sudo apt-get install -y singularity-container

      - name: Download flocs Singularity
        run: |
          singularity pull flocs.sif \
          https://public.spider.surfsara.nl/project/lofarvwf/fsweijen/containers/flocs_v5.5.1_znver2_znver2.sif

      - name: Run --help on main.py
        run: |
          singularity exec --bind $(pwd):/repo flocs.sif \
          python /repo/sidereal_visibility_avg/main.py --help

      - name: Run --help on h5_merger
        run: |
          singularity exec --bind $(pwd):/repo flocs.sif \
          python /repo/sidereal_visibility_avg/main.py /repo/.github/testdata/test?.ms

