name: Test SVA

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Disable Microsoft Repo
        run: |
          sudo sed -i 's/^deb/#deb/' /etc/apt/sources.list.d/microsoft-prod.list || true
          sudo apt-get update

      - name: Install Singularity
        run: |
          sudo apt-get install -y singularity-container

      - name: Download flocs Singularity
        run: singularity pull flocs.sif https://public.spider.surfsara.nl/project/lofarvwf/fsweijen/containers/flocs_ci.sif

      - name: Run --help on main.py
        run: |
          singularity exec --bind $(pwd):/repo flocs.sif bash -c "export PYTHONPATH=/repo:\$PYTHONPATH && python -m sidereal_visibility_avg.main --help"

      - name: Run testcase
        run: |
          singularity exec --bind $(pwd):/repo flocs.sif bash -c "export PYTHONPATH=/repo:\$PYTHONPATH && python -m sidereal_visibility_avg.main /repo/.github/testdata/test*.ms"

      - name: Run testcase with chunk factor
        run: |
          singularity exec --bind $(pwd):/repo flocs.sif bash -c "export PYTHONPATH=/repo:\$PYTHONPATH && python -m sidereal_visibility_avg.main --chunk_factor 2345.1 /repo/.github/testdata/test*.ms"
